default_language_version:
    python: python3
default_stages: [pre-commit, pre-push]
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.0
    hooks:
      - id: pydoclint
        args:
          - --check-return-types=False